[app]

# (str) Title of your application
title = تطبيقي الحديث

# (str) Package name
package.name = myapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (str) Application versioning (method 1)
version = 0.1

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,kivymd

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (list) Supported orientations
# Valid options are: landscape, portrait, portrait-reverse or landscape-reverse
orientation = portrait

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

#
# Android specific
#

# (list) Permissions
android.permissions = INTERNET

# (int) Target Android API, should be as high as possible.
android.api = 31

# (int) Minimum API your APK will support.
android.minapi = 21

# (str) Android NDK version to use
android.ndk = 23b

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
android.skip_update = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) python-for-android specific commit to use, defaults to HEAD, must be within p4a.branch
#p4a.commit = HEAD

# (str) python-for-android git clone directory
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =

# (str) Enable/disable Cython compilation for Python modules
#p4a.cython = 1

# (str) Enable/disable the inclusion of debug symbols in compiled Python modules
#p4a.debug_symbols = 1

#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the full path to a kivy-ios checkout
#ios.kivy_ios_dir = /Users/user/code/kivy-ios

# (str) If set, will customize the name of the resulting iOS Xcode project
#ios.custom_project_name = MyProject

# (str) Name of the certificate to use for signing the debug version
#ios.debug_signer = iPhone Developer

# (str) Name of the certificate to use for signing the release version
#ios.release_signer = iPhone Developer

# (str) Path to a custom .plist file to use for iOS
#ios.plist = CustomInfo.plist

# (bool) If True, kivy-ios will compile in Release mode.
#ios.release_mode = 1

# (str) Path to a custom kivy-ios module
#ios.kivy_ios_module =

# (str) If this is set, then the project will be built as a Framework instead of as a standalone app
#ios.framework = 1

# (bool) Whether to sign the iOS build
#ios.sign = 1

# (bool) If True, will automatically create a certificate if it doesn't exist
#ios.auto_sign = 1

# (str) The name of the certificate to use for signing
#ios.sign_identity =

# (str) The name of the provisioning profile to use for signing
#ios.provisioning_profile =

#
# macOS specific
#

# (str) Path to a custom kivy-macOS folder
#macos.kivy_macos_dir = ../kivy-macOS

# (str) If set, will customize the name of the resulting macOS Xcode project
#macos.custom_project_name = MyProject

# (bool) If True, kivy-macOS will compile in Release mode.
#macos.release_mode = 1

#
# Windows specific
#

# (str) Path to a custom kivy-windows folder
#windows.kivy_windows_dir = ../kivy-windows

# (str) If set, will customize the name of the resulting Windows package
#windows.custom_project_name = MyProject

# (bool) If True, kivy-windows will compile in Release mode.
#windows.release_mode = 1

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,kivymd

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (list) Supported orientations
# Valid options are: landscape, portrait, portrait-reverse or landscape-reverse
orientation = portrait

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0
